CREATE TABLE `changes` (
  `lastupdate` datetime DEFAULT null,
  `site` varchar(20) DEFAULT NULL,
  `evdate` varchar(50) DEFAULT NULL,
  `opp1` varchar(200) DEFAULT NULL,
  `opp2` varchar(200) DEFAULT NULL,
  `category` varchar(200) DEFAULT NULL,
  `market` varchar(200) DEFAULT NULL,
  `couponid` int(11) DEFAULT NULL,
  `eventdate` date DEFAULT NULL,
  `eventtime` time DEFAULT NULL,
  `eventwhen` datetime DEFAULT NULL,
  `price_from` decimal(8,3) DEFAULT NULL,
  `price_to` decimal(8,3) DEFAULT NULL,
  KEY `lastupdate` (`lastupdate`),
  KEY `site` (`site`),
  KEY `evdate` (`evdate`),
  KEY `opp1` (`opp1`),
  KEY `opp2` (`opp2`),
  KEY `market` (`market`),
  KEY `category` (`category`),
  KEY `eventdate` (`eventdate`),
  KEY `eventtime` (`eventtime`),
  KEY `couponid` (`couponid`),
  KEY `eventwhen` (`eventwhen`),
  KEY `price_from` (`price_from`),
  KEY `price_to` (`price_to`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
